//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Booking_Service
    {
        public int ID { get; set; }
        public string Booking { get; set; }
        public string ServiceID { get; set; }
    }
}
