//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Service
    {
        public string ID { get; set; }
        public string ServiceName { get; set; }
        public string Description { get; set; }
        public string Avatar { get; set; }
        public string Images { get; set; }
        public string ServiceType { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> DiscountID { get; set; }
    }
}
