//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Main
    {
        public int ID { get; set; }
        public string Content01 { get; set; }
        public string Image01 { get; set; }
        public string Content02 { get; set; }
        public string Image02 { get; set; }
        public string Title01 { get; set; }
        public string Title02 { get; set; }
    }
}
