//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Booking
    {
        public int ID { get; set; }
        public string RoomType { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string NumberOfAdult { get; set; }
        public string NumberOfChild { get; set; }
        public string VehicleTye { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ServiceID { get; set; }
        public string ActivityID { get; set; }
    }
}
