//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_About
    {
        public int ID { get; set; }
        public string LeftTitle { get; set; }
        public string LeftDescription { get; set; }
        public string RightTitle { get; set; }
        public string RightDescription { get; set; }
        public string Icon1 { get; set; }
        public string Title1 { get; set; }
        public string Description1 { get; set; }
        public string Icon2 { get; set; }
        public string Title2 { get; set; }
        public string Description2 { get; set; }
        public string Icon3 { get; set; }
        public string Title3 { get; set; }
        public string Description3 { get; set; }
        public string Icon4 { get; set; }
        public string Title4 { get; set; }
        public string Description4 { get; set; }
        public string Icon5 { get; set; }
        public string Title5 { get; set; }
        public string Description5 { get; set; }
        public string Icon6 { get; set; }
        public string Title6 { get; set; }
        public string Desciption6 { get; set; }
        public string BigTitle { get; set; }
        public string SubTitle { get; set; }
        public string Slogan { get; set; }
        public string Phone01 { get; set; }
        public string Phone02 { get; set; }
        public string Phone03 { get; set; }
    }
}
