//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Schedule
    {
        public int ID { get; set; }
        public string Schedule { get; set; }
        public string Status { get; set; }
        public Nullable<int> PriceDay { get; set; }
        public Nullable<int> PriceWeekend { get; set; }
        public Nullable<int> PriceHoliday { get; set; }
        public Nullable<int> AllInPirceDay { get; set; }
        public Nullable<int> AllInPirceWeekend { get; set; }
        public Nullable<int> AllInPirceHoliday { get; set; }
        public string Service { get; set; }
        public string AllInService { get; set; }
        public string TourType { get; set; }
        public string ServiceID { get; set; }
    }
}
