//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTL_Slider
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Title2 { get; set; }
        public string Slogan { get; set; }
        public string Slogan2 { get; set; }
        public string Icon { get; set; }
        public string Icon2 { get; set; }
        public string Images { get; set; }
        public string SubTitle { get; set; }
        public string SubTitle2 { get; set; }
    }
}
